sudo: enabled

services:
  - docker

env:
  - helmversion=v2.16.1

install:
  - docker pull lachlanevenson/k8s-helm:$helmversion

script:
  - docker run -v `pwd`:/opt/cgw --entrypoint "/bin/sh" lachlanevenson/k8s-helm:$helmversion -c  "cd /opt/cgw; helm init -c; helm repo add tp $CHART_REPO; helm package -u ."

deploy:
  provider: script
  script: bash -c 'curl --data-binary "@$(ls *.tgz)" $CHART_REPO/api/charts'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true