{{- if .Values.initScript.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "CGW.fullname" . }}-init-script
  labels:
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
    {{- end }}
data:
  initScript.sh: {{ .Values.initScript.script | quote}}
{{- end }}
