{{- if and .Values.ipsec.enabled .Values.ipsec.manualConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "CGW.fullname" . }}-strongswan-config
  labels:
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
    {{- end }}
data:
{{ toYaml .Values.ipsec.strongswan.ipsecConfig | indent 2 }}
{{- end -}}
